# 1-Numpy数组的属性
    确定数组的大小、形状、存储大小、数据类型

In [1]:
import numpy as np
np.random.seed(0) # 设置随机数种子，确保每次执行时都可以生成同样的随机数组

x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

每个数组有 nidm（数组的维度）、shape（数组每个维度的大小）和 size（数组的总大小）属性：

In [2]:
print(x3.ndim)# 数组的维度
print(x3.shape)#维度大小
print(x3.size)#总大小

3
(3, 4, 5)
60


In [3]:
# dtype 属性
x3.dtype

dtype('int32')

In [4]:
# 示每个数组元素字节大小的 itemsize，以及表示数组总字节大小的属性 nbytes：
print("itemsize:",x3.itemsize,"bytes")
print("nbytes:",x3.nbytes,"bytes")

itemsize: 4 bytes
nbytes: 240 bytes


可以认为 nbytes 跟 itemsize 和 size 的乘积大小相等

# 2-数组索引：获取单个元素

In [5]:
x1

array([5, 0, 3, 3, 7, 9])

In [6]:
x1[0]

5

In [7]:
x1[4]

7

In [8]:
# 为了获取数组末尾索引可以使用负值
x1[-1]

9

In [9]:
x1[-2]

7

In [10]:
# 在多维数组中，可以使用逗号分隔的索引元组3获取元素
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [11]:
x2[0,0]

3

In [12]:
x2[2,0]

1

In [13]:
x2[2,-1]

7

In [14]:
# 也可以使用以上方式来修改元素的值
x2[0,0]=12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [15]:
## 注意：
##    当试图将一个浮点值插入一个整型数组时，浮点值会被截短成整型，没有警告
x1[0]=3.1415926
x1

array([3, 0, 3, 3, 7, 9])

# 3-数组切片：获取子数组，用冒号':'
    获取数组 x 的一个切片：
    x[start:stop:step]

如果以上 3 个参数都未指定，那么它们会被分别设置默认值 start=0、stop= 维度的大小（size of dimension）和 step=1。

In [16]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# 前五个元素
x[:5]

array([0, 1, 2, 3, 4])

In [18]:
# 索引5之后的
x[5:]

array([5, 6, 7, 8, 9])

In [19]:
# 中间字数组
x[4:7]

array([4, 5, 6])

In [20]:
# 每隔一个元素
x[::2]

array([0, 2, 4, 6, 8])

In [21]:
# 每隔一个元素，从索引1开始
x[1::2]

array([1, 3, 5, 7, 9])

In [22]:
# 所有元素逆序
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [23]:
# 从索引5开始，每隔一个元素逆序
x[5::-2]

array([5, 3, 1])

In [24]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [25]:
# 两行，三列
x2[:2,:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [26]:
# 所有行，每隔一列
x2[:3,::2]  #同x2[::,::2]  ##同x2[:,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [27]:
# 逆序
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [28]:
# 第一列
x2[:,0]

array([12,  7,  1])

In [29]:
#第一行
x2[0,:]

array([12,  5,  2,  4])

In [30]:
# 可省略空的切片
x2[0] #  等价于x[0,:]

array([12,  5,  2,  4])

In [31]:
# 数组切片返回的是数组数据的视图，而不是数值数据的副本
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [32]:
# 抽取一个2*2的子数组
x2_sub = x2[:2,:2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [33]:
# 修改这个子数组，原始数组也被修改！！！
x2_sub[0,0]=99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [35]:
x2_sub_copy = x2[:2,:2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [36]:
x2_sub_copy[0,0]=42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [37]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


# 4-数组的变形
    通过reshape（）函数实现。

In [38]:
# 将数字1-9放入一个3*3的矩阵
grid = np.arange(1,10).reshape(3,3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


注意，该方法可行，那么原始数组的大小必须和变形后的数组大小一致

In [39]:
# 将一个一维数组转变为一个二维的行或列的矩阵
x = np.array([1,2,3])
x.reshape((1,3))

array([[1, 2, 3]])

In [40]:
# 通过newaxis获得行向量
x[np.newaxis,:]

array([[1, 2, 3]])

In [41]:
# 获得列向量
x.reshape((3,1))

array([[1],
       [2],
       [3]])

In [42]:
#通过newaxis获得列向量
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

# 5-数组的拼接和分裂

In [43]:
# 数组的拼接
# 拼接或连接主要由np.concatenate,np.vstack,np.hstack实现
x = np.array([1,2,3])
y = np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [44]:
# 一次拼接两个以上的数组
z = [99,99,99]
np.concatenate([x,y,z])

array([ 1,  2,  3,  3,  2,  1, 99, 99, 99])

In [45]:
# np.concatenate也可以拼接二维数组
grid = np.array([[1,2,3],[4,5,6]])

In [46]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [47]:
# 沿着第二个轴拼接、
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [48]:
# 沿着固定维度处理数组时，使用np.vstack(垂直栈)和np.hstack(水平栈)函数会更简洁
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

In [49]:
# 垂直栈
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [50]:
#水平栈
y = np.array([[99],[99]])
np.hstack([grid,y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

np.dstack将沿着第三维度拼接

In [51]:
# 数组的分裂
# 通过 np.split,np.hsplit,np.vsplit
# 可以向上函数传递一个索引列表作为参数，索引列表记录的是分裂点位置

In [52]:
x = [1,2,3,99,99,3,2,1]
x1,x2,x3=np.split(x,[3,5])
print(x1,x2,x3)

[1 2 3] [99 99] [3 2 1]


注意N个分裂点得到N+1个子数组

In [53]:
grid = np.arange(16).reshape((4,4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:
upper,lower = np.vsplit(grid,[2])
print(upper,lower)

[[0 1 2 3]
 [4 5 6 7]] [[ 8  9 10 11]
 [12 13 14 15]]


In [55]:
left,right = np.hsplit(grid,[2])
print(left,right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


np.dsplit将沿着第三维度分裂