# 1 缓慢的循环
    Python的相对缓慢通常出现在很多小操作需要不断重复时

In [1]:
# 如 对每个元素做循环操作，求倒数
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0/values[i]
    return output

values = np.random.randint(1,10,size=5)
print(values)
compute_reciprocals(values)

[6 1 4 4 8]


array([0.16666667, 1.        , 0.25      , 0.25      , 0.125     ])

以上方式实现，如果测试一个很大的输入数据运行上述代码的时间，是非常耗时的
    
通过 %timeit测量时间

In [2]:
big_array = np.random.randint(1,100,size=1000000)
%timeit compute_reciprocals(big_array)

1.9 s ± 47.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


# 2 通用函数的介绍
    NumPy 为很多类型的操作提供了非常方便的、静态类型的、可编译程序的接口，也被称作向量操作。
    对数组的操作将会被用于数组中的每一个元素。

In [3]:
# 比较以下两个结果
print(compute_reciprocals(values))
print(1.0/values)

[0.16666667 1.         0.25       0.25       0.125     ]
[0.16666667 1.         0.25       0.25       0.125     ]


In [4]:
# 如果计算一个较大数组的运行时间，可以看到它的完成时间比 Python 循环花费的时间更短：
%timeit (1.0/big_array)

4.25 ms ± 31.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


NumPy 中的向量操作是通过通用函数实现的。

In [5]:
# 也可以对两个数组进行运算
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [6]:
# 多维数组
x = np.arange(9).reshape((3,3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]], dtype=int32)

通过通用函数用向量的方式进行计算几乎总比用 Python 循环实现的计算更加有效，尤其是当数组很大时。

# 3 探索NumPy的通用函数
    一元通用函数和二元通用函数

In [7]:
# 标准的加、减、乘、除都可以使用
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [8]:
#逻辑非、** 表示的指数运算符和 % 表示的模运算符的一元通用函数
print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print('2 ** x = ',2 ** x)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
2 ** x =  [1 2 4 8]
x % 2 =  [0 1 0 1]


In [9]:
# 可以任意将这些算术运算符组合使用
-(0.5*x+1)**2

array([-1.  , -2.25, -4.  , -6.25])

注 所有的算术运算符都是NumPy内置函数的简单封装器

In [10]:
# + 运算符就是一个 add 函数的封装器
np.add(x,2)

array([2, 3, 4, 5])

In [11]:
# 内置绝对值函数
x = np.array([-2,-1,0,1,2])
abs(x)

array([2, 1, 0, 1, 2])

对应的 NumPy 通用函数是 np.absolute，该函数也可以用别名 np.abs 来访问

In [12]:
np.absolute(x)

array([2, 1, 0, 1, 2])

In [13]:
np.abs(x)

array([2, 1, 0, 1, 2])

In [14]:
# 这个通用函数也可以处理复数。当处理复数时，绝对值返回的是该复数的幅度
x = np.array([3-4j,4-3j,2+0j,0+1j])
np.abs(x)

array([5., 5., 2., 1.])

In [15]:
# 定义一个角度数组
theta = np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [16]:
print('theta      = ', theta)
print('sin(theta) = ', np.sin(theta))
print('cos(theta) = ', np.cos(theta))
print('tan(theta) = ', np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [17]:
# 逆三角函数
x = [-1,0,1]
print('x         = ', x)
print('arcsin(x) = ', np.arcsin(x))
print('arccos(x) = ', np.arccos(x))
print('arctan(x) = ', np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


In [18]:
# 指数对对数
x = [1,2,3]
print("x   = ", x)
print('e^x = ', np.exp(x))
print('2^x = ', np.exp2(x))
print('3^x = ', np.power(3,x))

x   =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]


In [19]:
x = [1,2,4,10]
print('x        = ', x)
print('ln(x)    = ', np.log(x))
print('log2(x)  = ', np.log2(x))
print('log10(x) = ', np.log10(x))

x        =  [1, 2, 4, 10]
ln(x)    =  [0.         0.69314718 1.38629436 2.30258509]
log2(x)  =  [0.         1.         2.         3.32192809]
log10(x) =  [0.         0.30103    0.60205999 1.        ]


In [20]:
# 还有一些特殊的版本，对于非常小的输入值可以保持较好的精度
x = [0,0.001,0.01,0.1]
print('exp(x) - 1  =', np.expm1(x))
print('log(1 + x)  =', np.log1p(x))

exp(x) - 1  = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x)  = [0.         0.0009995  0.00995033 0.09531018]


注 当 x 的值很小时，以上函数给出的值比 np.log 和 np.exp 的计算更精确。
    
专用的通用函数（双曲三角函数、比特位运算、比较运算符、弧度转化为角度的运算、取整和求余运算）
    
如果你希望对你的数据进行一些更晦涩的数学计算，scipy.special 可能包含了你需要的计算函数。

In [21]:
from scipy import special

In [22]:
# Gamma 函数  （广义阶乘，generalized factorials）和相关函数
x = [1,5,10]
print('gamma(x)       = ', special.gamma(x))
print('ln|gamma(x)|   = ', special.gammaln(x))
print('beta(x,2)      = ', special.beta(x, 2))

gamma(x)       =  [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)|   =  [ 0.          3.17805383 12.80182748]
beta(x,2)      =  [0.5        0.03333333 0.00909091]


In [23]:
# 误差函数（高斯积分）
# 它的实现和它的逆实现
x = np.array([0,0.3,0.7,1])
print('erf(x)     = ', special.erf(x))
print('erfc(x)    = ', special.erfc(x))
print('erfinv(x)  = ', special.erfinv(x))

erf(x)     =  [0.         0.32862676 0.67780119 0.84270079]
erfc(x)    =  [1.         0.67137324 0.32219881 0.15729921]
erfinv(x)  =  [0.         0.27246271 0.73286908        inf]


# 4-高级的通用函数特性

1-指定输出
 
    在进行大量运算时，有时候指定一个用于存放运算结果的数组是非常有用的。
    
    可以用这个特性将计算结果直接写入到你期望的存储位置。
    
    所有的通用函数都可以通过 out 参数来指定计算结果的存放位置。

In [24]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [25]:
# 可以将计算结果写入指定数组的每个一个元素的位置
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


2-聚合
    
    一个 reduce 方法会对给定的元素和操作重复执行，直至得到单个的结果。

In [26]:
# 对 add 通用函数调用 reduce 方法会返回数组中所有元素的和
x = np.arange(1,6)
np.add.reduce(x)

15

In [27]:
# 对 multiply 通用函数调用 reduce 方法会返回数组中所有元素的乘积
np.multiply.reduce(x)

120

In [28]:
# 如果需要存储每次计算的中间结果，可以使用 accumulate
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [29]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

3-外积
    
    任何通用函数都可以用 outer 方法获得两个不同输入数组所有元素对的函数运算结果。

In [30]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])