# 1 Python不仅仅是一个列表

In [1]:
# 如下方式创建一个整型值列表
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [3]:
# 创建一个字符串列表
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(L2[0])

str

In [5]:
L3 = [True,'2',3.0,4]
[type(item) for item in L3]

[bool, str, float, int]

# 2 Python中的固定类型数组
    内置的数组array模块可以用于创建统一类型的密集数组

In [6]:
import array
L = list(range(10))
A = array.array('i',L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

注 这里的‘i’是一个数据类型码

In [7]:
# 别名
import numpy as np

# 3 从Python列表创建数组

In [8]:
# 可以用np.array从Python列表创建数组
np.array([1,4,2,5,3])

array([1, 4, 2, 5, 3])

In [9]:
np.array([2.14,3,4,2])

array([2.14, 3.  , 4.  , 2.  ])

In [10]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [11]:
# 多维
np.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

# 4 从头创建数组

In [12]:
#创建一个长度为10的数组，数组的值全是0
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
#创建一个3*5的浮点数组，数组的值全是1
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
#创建一个3*5的浮点数组，数组的值全是3.14
np.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
#创建一个3*5的浮点数组，数组的值是一个线性序列
#从0开始，到20结束，步长2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
#创建一个5个元素的数组，这五个元素均匀分配到0-1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
#创建一个3*3的，在0-1上均匀分布的随机数组组成的数组
np.random.random((3,3))

array([[0.70434644, 0.0139975 , 0.44805612],
       [0.8492658 , 0.82942892, 0.80457321],
       [0.1036516 , 0.27534381, 0.36165836]])

In [18]:
#创建一个3*3的，均值0，方差1的正态分布随机数数组
np.random.normal(0,1,(3,3))

array([[ 1.36329632,  0.51724937, -1.41149181],
       [-0.95186564, -0.149164  , -1.25395987],
       [ 0.44867884, -0.86305752, -1.28247815]])

In [19]:
#创建一个3*3的，0-10区间的随机整形数组
np.random.randint(0,10,(3,3))

array([[6, 9, 3],
       [5, 9, 7],
       [6, 3, 5]])

In [20]:
#3*3的单位阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
#创建一个由3个整型数组组成的未初始化的数组
#数组的值是内存空间的任意值
np.empty(3)

array([1., 1., 1.])